# Flutter GitHub Action by Alexander Abraham,
# a.k.a. The Black Unicorn,
# a.k.a. Angeldust Duke.
# Licensed under the MIT license.

name: Flutter Build CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy a Flutter app.
    steps:
      - uses: actions/checkout@v3
      - id: build
        name: Site compilation.
        run: wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.0.1-stable.tar.xz && tar xf flutter_linux_3.0.1-stable.tar.xz && ls && export PATH="$PATH:`pwd`/flutter/bin" && flutter -v && flutter config --no-analytics && rm -rf *.tar.xz && flutter build web && ls
        shell: bash
